// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview8.19405.11");

            modelBuilder.Entity("Domain.WeatherForcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeatherForcasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2019, 9, 3, 14, 58, 33, 673, DateTimeKind.Local).AddTicks(4380),
                            Summary = "It is warm out today",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2019, 9, 2, 14, 58, 33, 675, DateTimeKind.Local).AddTicks(5041),
                            Summary = "It is cold out today",
                            TemperatureC = 20
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2019, 9, 1, 14, 58, 33, 675, DateTimeKind.Local).AddTicks(5142),
                            Summary = "It is HOT out today",
                            TemperatureC = 45
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
